// Bundles the iframe runtime (React + SDK + UI kit + boot) into a single IIFE
// served same-origin by the shell: apps/shell/public/vendor/runtime.js
import { build, context } from "esbuild";
import { mkdirSync, readFileSync, writeFileSync } from "node:fs";
import { fileURLToPath } from "node:url";
import path from "node:path";

const root = path.dirname(path.dirname(fileURLToPath(import.meta.url)));
const outdir = path.join(root, "apps/shell/public/vendor");
mkdirSync(outdir, { recursive: true });

const runtimeOutfile = path.join(outdir, "runtime.js");
const runtimeAssetFile = path.join(root, "convex/lib/runtimeAsset.ts");

const convexAssetPlugin = {
  name: "convex-runtime-asset",
  setup(build) {
    build.onEnd((result) => {
      if (result.errors.length > 0) return;
      const runtimeJs = readFileSync(runtimeOutfile, "utf8");
      writeFileSync(
        runtimeAssetFile,
        `// GENERATED by scripts/build-vendor.mjs — do not edit.\nexport const RUNTIME_JS: string = ${JSON.stringify(runtimeJs)};\n`,
      );
    });
  },
};

const opts = {
  entryPoints: [path.join(root, "packages/runtime-sdk/src/boot.tsx")],
  bundle: true,
  format: "iife",
  outfile: runtimeOutfile,
  minify: true,
  sourcemap: false,
  define: { "process.env.NODE_ENV": '"production"' },
  logLevel: "info",
  plugins: [convexAssetPlugin],
};

if (process.argv.includes("--watch")) {
  const ctx = await context(opts);
  await ctx.watch();
  console.log("vendor: watching runtime.js");
} else {
  await build(opts);
  console.log("vendor: built runtime.js");
}
