// Reads skills/DEVIN_SYSTEM*.md + skills/skill-*.md and emits
// convex/lib/skillsData.ts so Convex actions can compose Devin prompts.
import { readFileSync, readdirSync, writeFileSync } from "node:fs";
import { fileURLToPath } from "node:url";
import path from "node:path";

const root = path.dirname(path.dirname(fileURLToPath(import.meta.url)));
const skillsDir = path.join(root, "skills");

function parseFrontmatter(src) {
  const m = src.match(/^---\n([\s\S]*?)\n---\n?/);
  if (!m) return { meta: {}, body: src };
  const meta = {};
  for (const line of m[1].split("\n")) {
    const kv = line.match(/^(\w[\w-]*):\s*(.*)$/);
    if (!kv) continue;
    const [, k, raw] = kv;
    if (raw.startsWith("[")) {
      meta[k] = raw
        .slice(1, -1)
        .split(",")
        .map((s) => s.trim().replace(/^["']|["']$/g, ""))
        .filter(Boolean);
    } else {
      meta[k] = raw.trim();
    }
  }
  return { meta, body: src.slice(m[0].length) };
}

const system = readFileSync(path.join(skillsDir, "DEVIN_SYSTEM.md"), "utf8");
const systemInline = readFileSync(path.join(skillsDir, "DEVIN_SYSTEM_INLINE.md"), "utf8");
const skills = [];
for (const f of readdirSync(skillsDir).sort()) {
  if (!f.startsWith("skill-") || !f.endsWith(".md")) continue;
  const { meta, body } = parseFrontmatter(readFileSync(path.join(skillsDir, f), "utf8"));
  skills.push({
    name: meta.name ?? f.replace(/^skill-|\.md$/g, ""),
    triggers: Array.isArray(meta.triggers) ? meta.triggers : [],
    requires: Array.isArray(meta.requires) ? meta.requires : [],
    core: String(meta.core ?? "false") === "true",
    priority: Number.isFinite(Number(meta.priority)) ? Number(meta.priority) : 0,
    content: body.trim(),
  });
}

const out = `// GENERATED by scripts/build-skills.mjs — do not edit by hand. Edit skills/*.md instead.
export const SYSTEM: string = ${JSON.stringify(system)};
export const SYSTEM_INLINE: string = ${JSON.stringify(systemInline)};
export const SKILLS: Array<{ name: string; triggers: string[]; requires: string[]; core: boolean; priority: number; content: string }> = ${JSON.stringify(
  skills,
  null,
  2
)};
`;
writeFileSync(path.join(root, "convex/lib/skillsData.ts"), out);
console.log(`skills: ${skills.length} skills + full/inline system prompts -> convex/lib/skillsData.ts`);
